### PR TITLE
Add support for IORING_REGISTER_IOWQ_AFF

### PR DESCRIPTION
**Pull request by mjasny**
Hi,

I found that methods to specify cores for async workers are missing in this library.

Manpage: https://manpages.debian.org/unstable/liburing-dev/io_uring_register.2.en.html#IORING_REGISTER_IOWQ_AFF
Usage example in liburing: https://github.com/axboe/liburing/blob/cb00b6d807efaaaa5455223bf28a73fa216b2d24/test/wq-aff.c#L106

I decided to pull the libc::cpu_set_t related code into `register_iowq_aff`. If you think this is a bad idea, I'm happy to adapt the pull-request.

### CODE REVIEW

**Comment by quininer** [comment]
I think it would be better to just pass a `cpu_set_t`. can you add a test?

**Comment by mjasny** [comment]
I modified the patch, such that the function accepts a `cpu_set_t`.

A test for setting the cpu mask of async workers is already in liburing itself (see second link above). However, if I would port this test to the `io-uring-test` package this would require a rewrite of the whole test-suite because a ring with sqpoll enabled is required. Please correct me if I'm wrong.

**Comment by quininer** [comment]
You can create a new ring and write a simple test.

**Comment by quininer** [comment]
Anyway, I'll merge it first. Thank you!

**Pull request merged**
