### PR TITLE
inline Entry::clone

### PR DESCRIPTION
**Pull request by s3bk**
It showed up in in the profiler.

### CODE REVIEW

**Comment by quininer** [comment]
Thanks for the PR, I have fixed the ci issue on master, can you rebase it?

**Comment by s3bk** [comment]
Not exactly what you requested, but I am a git noob... I hope it works.
I also have another PR ready once this is done to address the repeated flag reads.

**Comment by s3bk** [comment]
Or just add the inline yourself, a PR is overkill.

**Comment by quininer** [comment]
Thank you!

**Pull request merged**
