### PR TITLE
Add notif and related SendZc docs

### PR DESCRIPTION
**Pull request by erenon**
- **Add notif that checks for IORING_CQE_F_NOTIF**
- **Add extra documentation to SendZc**

### CODE REVIEW

**Comment by quininer** [comment]
Can you add a test? and you don't need to add much docs, just point to manpage of IORING_OP_SEND_ZC.

**Comment by erenon** [comment]
Added a test. I have two issues with just linking the docs:

 - The quoted paragraph is in the middle of https://man7.org/linux/man-pages/man2/io_uring_enter.2.html , and I can't link that section directly (there's no anchor in the HTML)
 - Even if I link the doc, it wouldn't make the "notif" fn added by this PR discoverable

I find this doc+notif to be visible important, because without these, SendZc cannot be used correctly. If you feel strongly about keeping the doc minimal, I can of course replace the paragraph with a link, let me know.

**Comment by quininer** [comment]
I don't have the energy to keep track of upstream docs, so I prefer to keep minimal description and point to correct upstream docs.

**Comment by erenon** [comment]
Got it. Added a link instead of the text.

**Comment by erenon** [comment]
fmt fixed (extra newline removed)

**Comment by quininer** [comment]
Thank you!

**Pull request merged**
